version: "3.8"
services:
  terraform:
    container_name: terraform
    build: .
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    environment:
      TZ: ${TZ}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
